# *** DEV ***

services:
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
      args:
        - REDIS_PASS=${REDIS_PASS}
    volumes:
      - redis_data:/data
    ports:
      - ${REDIS_PUB_PORT}:6379

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${PG_PUB_PORT}:5432

  api:
    build:
      context: ../..
      dockerfile: docker/dev/api/Dockerfile
    volumes:
      - ../../:/home/node/api
    ports:
      - ${API_PUB_PORT}:3000
      - ${API_PUB_DEBUG_PORT}:9229
    depends_on:
      - redis
      - postgres

volumes:
  redis_data:
  postgres_data:
