# *** DEV ***

services:
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    container_name: redis
    ports:
      - ${REDIS_PORT}:6379
    command: ['redis-server', '--protected-mode', 'no', '--requirepass', '${REDIS_PASS}']

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: postgres
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${PG_PORT}:5432

volumes:
  postgres_data:
