services:
  api:
    build:
      context: ../
      dockerfile: ./Dockerfile
    container_name: api
    volumes:
      - ../:/home/node/api
    env_file:
      - .api.env
    command: ['/home/node/api/dev/command.sh']
    ports:
      - ${API_PORT}:${API_PORT}
      - ${API_DEBUG_PORT}:${API_DEBUG_PORT}
