services:
  api:
    build:
      context: ../
      dockerfile: ./Dockerfile
    volumes:
      - ../:/home/node/api
    env_file:
      - .api.env
    command: ['/home/node/api/dev/command.sh']
    ports:
      - ${PUBLIC_PORT}:${PUBLIC_PORT}
      - ${PUBLIC_DEBUG_PORT}:${PUBLIC_DEBUG_PORT}
