# *** PROD ***

services:
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - ${REDIS_PUB_PORT}:6379
    command: ['redis-server', '--protected-mode', 'no', '--requirepass', '${REDIS_PASS}']

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${PG_PUB_PORT}:5432

  api:
    build:
      context: ../..
      dockerfile: docker/prod/api/Dockerfile
    depends_on:
      - redis
      - postgres

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - ${NGINX_PUB_HTTP_PORT}:80
      - ${NGINX_PUB_HTTPS_PORT}:443
    depends_on:
      - api

volumes:
  postgres_data:
